/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formui;

import lib.adapter.*;

/**
 *
 * @author javauser
 */
public class CalcolatriceJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CalcolatriceJFrame
     */
    public CalcolatriceJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPrimoOperando = new javax.swing.JTextField();
        txtSecondoOperando = new javax.swing.JTextField();
        txtRisultato = new javax.swing.JTextField();
        lblPrimoOperando = new javax.swing.JLabel();
        lblSecondoOperando = new javax.swing.JLabel();
        lblRisultato = new javax.swing.JLabel();
        btnSomma = new javax.swing.JButton();
        btnSottrai = new javax.swing.JButton();
        btnMoltiplica = new javax.swing.JButton();
        btnDividi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPrimoOperando.setText("Primo operando:");

        lblSecondoOperando.setText("Secondo operando:");

        lblRisultato.setText("Risultato:");

        btnSomma.setText("+");
        btnSomma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSommaActionPerformed(evt);
            }
        });

        btnSottrai.setText("-");
        btnSottrai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSottraiActionPerformed(evt);
            }
        });

        btnMoltiplica.setText("*");
        btnMoltiplica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoltiplicaActionPerformed(evt);
            }
        });

        btnDividi.setText("/");
        btnDividi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRisultato)
                        .addGap(111, 111, 111)
                        .addComponent(txtRisultato, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSecondoOperando)
                        .addGap(45, 45, 45)
                        .addComponent(txtSecondoOperando, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPrimoOperando)
                        .addGap(64, 64, 64)
                        .addComponent(txtPrimoOperando, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSomma, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSottrai, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMoltiplica, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDividi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrimoOperando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrimoOperando))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSecondoOperando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSecondoOperando))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSomma)
                    .addComponent(btnSottrai)
                    .addComponent(btnDividi)
                    .addComponent(btnMoltiplica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRisultato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRisultato))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSommaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSommaActionPerformed
    	txtRisultato.setText(CalcolatriceAdapter.somma(txtPrimoOperando.getText(), txtSecondoOperando.getText())); 
    }//GEN-LAST:event_btnSommaActionPerformed

    private void btnSottraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSottraiActionPerformed
    	txtRisultato.setText(CalcolatriceAdapter.sottrai(txtPrimoOperando.getText(), txtSecondoOperando.getText()));
    }//GEN-LAST:event_btnSottraiActionPerformed

    private void btnMoltiplicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoltiplicaActionPerformed
    	txtRisultato.setText(CalcolatriceAdapter.moltiplica(txtPrimoOperando.getText(), txtSecondoOperando.getText()));
    }//GEN-LAST:event_btnMoltiplicaActionPerformed
    
    private void btnDividiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividiActionPerformed
    	txtRisultato.setText(CalcolatriceAdapter.dividi(txtPrimoOperando.getText(), txtSecondoOperando.getText()));
    }//GEN-LAST:event_btnDividiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcolatriceJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcolatriceJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcolatriceJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcolatriceJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcolatriceJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDividi;
    private javax.swing.JButton btnMoltiplica;
    private javax.swing.JButton btnSomma;
    private javax.swing.JButton btnSottrai;
    private javax.swing.JLabel lblPrimoOperando;
    private javax.swing.JLabel lblRisultato;
    private javax.swing.JLabel lblSecondoOperando;
    private javax.swing.JTextField txtPrimoOperando;
    private javax.swing.JTextField txtRisultato;
    private javax.swing.JTextField txtSecondoOperando;
    // End of variables declaration//GEN-END:variables
}
